sudo: required
dist: trusty
language: c
matrix:
  include:
  - os: linux
    env: TESTENV=py34-cov
  - os: linux
    env: DOCKER=debian-jessie
    services: docker
  - os: linux
    env: DOCKER=archlinux
    services: docker
  - os: linux
    env: DOCKER=ubuntu-wily
    services: docker
  - os: osx
    env: TESTENV=py35
  - os: linux
    env: TESTENV=pylint
  - os: linux
    env: TESTENV=flake8
  - os: linux
    env: TESTENV=docs
  - os: linux
    env: TESTENV=vulture
  - os: linux
    env: TESTENV=misc
  - os: linux
    env: TESTENV=pyroma
  - os: linux
    env: TESTENV=check-manifest
  - os: linux
    env: TESTENV=eslint
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/build/The-Compiler/qutebrowser/.cache
before_install:
- export PATH="/usr/bin:$PATH"
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
install:
- python scripts/dev/ci/install.py
before_script:
- bash test_mypy.sh
script:
- echo "SCRIPT SECTION"
