dist: xenial
language: python
group: edge
python: 3.8
os: linux
matrix:
  fast_finish: true
  include:
  - env: DOCKER=archlinux
    services: docker
  - env: DOCKER=archlinux-webengine QUTE_BDD_WEBENGINE=true
    services: docker
  - python: 3.5
    env: TESTENV=py35-pyqt57
  - python: 3.6
    env: TESTENV=py36-pyqt59
  - python: 3.6
    env: TESTENV=py36-pyqt510
    addons:
      apt:
        packages:
        - xfonts-base
  - python: 3.7
    env: TESTENV=py37-pyqt511
  - env: TESTENV=py38-pyqt512
    addons:
      apt:
        packages:
        - libxkbcommon-x11-0
  - env: TESTENV=py38-pyqt513-cov
    addons:
      apt:
        packages:
        - libxkbcommon-x11-0
  - os: osx
    env: TESTENV=py37-pyqt513 OSX=sierra
    osx_image: xcode9.2
    language: generic
    python: 3.7
  - env: TESTENV=pylint
  - env: TESTENV=flake8
  - env: TESTENV=mypy
  - env: TESTENV=docs
    addons:
      apt:
        packages:
        - asciidoc
  - env: TESTENV=vulture
  - env: TESTENV=misc
  - env: TESTENV=pyroma
  - env: TESTENV=check-manifest
  - env: TESTENV=eslint
    language: node_js
    python: null
    node_js: lts/*
  - language: generic
    env: TESTENV=shellcheck
    services: docker
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/build/qutebrowser/qutebrowser/.cache
install:
- bash scripts/dev/ci/travis_install.sh
- ulimit -c unlimited
before_script:
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- echo "SCRIPT SECTION"
