sudo: required
dist: trusty
language: generic
matrix:
  include:
  - os: linux
    env: TESTENV=py34-cov
  - os: linux
    env: DOCKER=debian-jessie
    services: docker
  - os: linux
    env: DOCKER=archlinux
    services: docker
  - os: linux
    env: DOCKER=archlinux-webengine QUTE_BDD_WEBENGINE=true
    services: docker
  - os: linux
    env: DOCKER=archlinux-ng
    services: docker
  - os: linux
    env: DOCKER=ubuntu-xenial
    services: docker
  - os: linux
    language: python
    python: 3.6
    env: TESTENV=py36-pyqt571
  - os: linux
    language: python
    python: 3.5
    env: TESTENV=py35-pyqt58
  - os: linux
    language: python
    python: 3.6
    env: TESTENV=py36-pyqt58
  - os: osx
    env: TESTENV=py36 OSX=elcapitan
    osx_image: xcode7.3
  - os: linux
    env: TESTENV=pylint
  - os: linux
    env: TESTENV=flake8
  - os: linux
    env: TESTENV=docs
  - os: linux
    env: TESTENV=vulture
  - os: linux
    env: TESTENV=misc
  - os: linux
    env: TESTENV=pyroma
  - os: linux
    env: TESTENV=check-manifest
  - os: linux
    env: TESTENV=eslint
  fast_finish: true
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/build/qutebrowser/qutebrowser/.cache
before_install:
- export PATH="/usr/bin:$PATH"
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
install:
- bash scripts/dev/ci/travis_install.sh
- ulimit -c unlimited
before_script:
- bash test_mypy.sh
script:
- echo "SCRIPT SECTION"
