dist: xenial
language: python
group: edge
python: 3.6
matrix:
  include:
  - os: linux
    env: DOCKER=archlinux
    services: docker
  - os: linux
    env: DOCKER=archlinux-webengine QUTE_BDD_WEBENGINE=true
    services: docker
  - os: linux
    env: TESTENV=py36-pyqt571
  - os: linux
    python: 3.5
    env: TESTENV=py35-pyqt571
  - os: linux
    env: TESTENV=py36-pyqt59
  - os: linux
    env: TESTENV=py36-pyqt510
    addons:
      apt:
        packages:
        - xfonts-base
  - os: linux
    env: TESTENV=py36-pyqt511-cov
  - os: linux
    python: 3.7
    env: TESTENV=py37-pyqt511
  - os: osx
    env: TESTENV=py37 OSX=sierra
    osx_image: xcode9.2
    language: generic
  - os: linux
    env: TESTENV=pylint PYTHON=python3.6
  - os: linux
    env: TESTENV=flake8
  - os: linux
    env: TESTENV=docs
    addons:
      apt:
        packages:
        - asciidoc
  - os: linux
    env: TESTENV=vulture
  - os: linux
    env: TESTENV=misc
  - os: linux
    env: TESTENV=pyroma
  - os: linux
    env: TESTENV=check-manifest
  - os: linux
    env: TESTENV=eslint
    language: node_js
    python: null
    node_js: lts/*
  - os: linux
    language: generic
    env: TESTENV=shellcheck
    services: docker
  fast_finish: true
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/build/qutebrowser/qutebrowser/.cache
install:
- bash scripts/dev/ci/travis_install.sh
- ulimit -c unlimited
before_script:
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- echo "SCRIPT SECTION"
