dist: xenial
language: python
python: 3.5
os: linux
env: TESTENV=py35-pyqt57
install:
- python -m pip install -U pip
- python -m pip install -U -r misc/requirements/requirements-tox.txt
- ulimit -c unlimited
before_script:
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- echo "SCRIPT SECTION"
